apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/5 * * * *"  # Cron schedule (every day)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image:  gcr.io/cloudcoursework-409406/todynamobb_image2:v1
          restartPolicy: OnFailure
