#CICD
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.TODYNAMOBB_PROJECT }}
  MY_CLUSTER: mycluster
  MY_ZONE: us-central1
  DEPLOYMENT_NAME: todynamobb2
  IMAGE: todynamobb_image2
  TAG: v1


jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.TODYNAMOBB_KEY}}
          project_id: ${{secrets.TODYNAMOBB_PROJECT}}

      - name: Configure Docker in GKE
        run: gcloud --quiet auth configure-docker

      - name: Get SI Credentials GKE
        run: gcloud container clusters get-credentials "$MY_CLUSTER" --zone "$MY_ZONE"

      # Build the Docker image
      - name: Build Docker Image GCR
        run: |-
          docker build --tag gcr.io/$PROJECT_ID/todynamobb_image2:v1 .

      - name: Publish Docker Image to GCR
        run: |-
          docker push gcr.io/$PROJECT_ID/todynamobb_image2:v1

#      - name: Set up Kustomize
#        run: |-
#          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
#          chmod u+x ./kustomize

      - name: Install Gcloud Component
        run: |-
          gcloud components install gke-gcloud-auth-plugin

#      - name: Deploy Image to GKE cluster
#        run: |-
#          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout restart deployment $DEPLOYMENT_NAME
#          kubectl get services -o wide

      - name: Deploy Image to GKE cluster
        run: |-
          kubectl apply -f cronjob.yaml
#         kubectl apply -f service.yaml
#         kubectl rollout restart deployment $DEPLOYMENT_NAME
#         kubectl get services -o wide
